### ISSUE TITLE
Google Colab Error: ModuleNotFoundError: No module named 'clip'

### ISSUE THREAD

**Issue by lanzjose** [Blucknote/Kandinsky-advanced-notebooks#1]
![clip](https://user-images.githubusercontent.com/60416752/235737122-2c66f7db-9f9e-4837-b2ed-2b0b82241f3a.png)

**Comment by Blucknote** [comment]
I'm not tried collab but clip requirement definetely here
https://github.com/Blucknote/Kandinsky-advanced-notebooks/blob/55a7654af8f1ebe613a6fe89a7bec08c78fd66f8/requirements.txt#L1

Try to `!pip install -r requirements.txt` in some cell.

I'm also updated requirements.txt for missing opencv, so you need to pull this changes.
